version: "3"
services:
  web:
    container_name: app-180611-web
    build: "."
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - "./wordpress:/var/www/html"
  db:
    container_name: app-180611-db
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-180611
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./db-data:/var/lib/mysql"
